In [1]:
from bs4 import BeautifulSoup as bs
import pandas as pd
import numpy as np
import os
import io
import builtins
import time
import re
from itertools import product
import dash
from dash import dcc
from dash import html 
from dash import dash_table
import dash_bootstrap_components as dbc
from datetime import datetime


from dash.dependencies import Input, Output
pd.set_option('display.max_rows', 150)
pd.set_option('display.max_columns', 63)

In [2]:
python_exports = "C:/Users/jackj/Documents/Sports Interactive/Football Manager 2024/Python Exports"
current_save = "Havant - GS"
all_players_file = "all_players_data.csv"
folder_path = python_exports + "/" + current_save
all_players_file_path = folder_path+"/all_players/" + all_players_file
all_folder_files = os.listdir(folder_path)
all_csv_files = [f for f in all_folder_files if f.endswith('.csv')]    
all_csv_files = [w.replace('.csv', '') + ' 00:00:01' for w in all_csv_files]

In [3]:
if not os.path.exists(all_players_file_path):
    exported_dates = pd.DataFrame({'Date': [1, 2]})

else:
    # If the file exists, read the existing data and make a copy    
    exported_dates = pd.read_csv(all_players_file_path)

exported_dates = exported_dates.Date.unique().tolist()
print(exported_dates)

['2024-07-01 00:00:01', '2024-10-01 00:00:01']

In [4]:
for file in all_csv_files:
    if file not in exported_dates:
        file_name = file.replace(' 00:00:01','')
        full_path = folder_path + '/' + file_name + '.csv'
        raw_table = pd.read_csv(full_path, sep=';', encoding='latin1')        
        date = file_name.split('.')[0] +  ' 00:00:01'
        raw_table['Date'] = pd.to_datetime(date, format = "%Y-%m-%d %H:%M:%S")
        raw_table['DoB'] = pd.to_datetime(raw_table['Date Of Birth'], dayfirst=True, errors='coerce')
        raw_table['Age'] = (raw_table['Date']-raw_table['DoB']).dt.days/365.25

        if not os.path.exists(all_players_file_path):
            raw_table.to_csv(all_players_file_path, index=False)
            print(f"Created file: {all_players_file_path}")
        else:
            # If the file exists, read the existing data and make a copy
            timestr = time.strftime("%Y%m%d-%H%M%S")
            existing_df = pd.read_csv(all_players_file_path)


            # Union the existing DataFrame with the new DataFrame
            combined_df = pd.concat([existing_df, raw_table]).drop_duplicates().reset_index(drop=True)

            # Save the combined DataFrame back to the CSV file
            combined_df.to_csv(all_players_file_path, index=False)
            print(f"Updated file: {all_players_file_path}")

Updated file: C:/Users/jackj/Documents/Sports Interactive/Football Manager 2024/Python Exports/Havant - GS/all_players/all_players_data.csv

In [5]:
all_players_table = pd.read_csv(all_players_file_path)
all_players_table

,Unique ID,Name,Position,Date Of Birth,Wage,GK Rating,DL Rating,DC Rating,DR Rating,WBL Rating,WBR Rating,DM Rating,ML Rating,MC Rating,MR Rating,AML Rating,AMC Rating,AMR Rating,FS Rating,GK Pot Rating,DL Pot Rating,DC Pot Rating,DR Pot Rating,WBL Pot Rating,WBR Pot Rating,DM Pot Rating,ML Pot Rating,MC Pot Rating,MR Pot Rating,AML Pot Rating,AMC Pot Rating,AMR Pot Rating,FS Pot Rating,Date,DoB,Age
0,2000138022,"Willson, Brendan",D C,01.07.2003,190,23.19%,40.51%,50.63%,40.51%,40.51%,40.51%,44.22%,37.97%,0.00%,37.97%,37.97%,37.97%,37.97%,37.97%,23.49%,40.89%,51.11%,40.89%,40.89%,40.89%,44.64%,38.30%,0.00%,38.30%,38.30%,38.30%,38.30%,38.30%,2024-07-01 00:00:01,2003-07-01,21.002053
1,43273316,"Faal, Muhammadu","AM RL, ST",01.07.1997,850,33.31%,50.16%,50.16%,50.16%,50.16%,50.16%,50.16%,55.65%,0.00%,55.05%,60.43%,48.69%,59.69%,61.81%,35.53%,53.37%,53.37%,53.37%,53.37%,53.37%,53.37%,59.34%,0.00%,58.71%,64.45%,51.92%,63.66%,65.85%,2024-07-01 00:00:01,1997-07-01,27.000684
2,29192118,"Woollard-Innocent, Kai",D/WB L,28.09.2000,490,27.24%,52.89%,48.64%,42.31%,52.71%,42.31%,42.31%,40.72%,0.00%,40.72%,40.72%,40.72%,40.72%,40.72%,30.51%,58.10%,53.43%,46.48%,57.90%,46.48%,46.48%,44.93%,0.00%,44.93%,44.93%,44.93%,44.93%,44.93%,2024-07-01 00:00:01,2000-09-28,23.756331
3,2000231345,"Odei-Larbi, Joel","AM L, ST",27.07.2006,0,29.76%,47.80%,47.80%,47.80%,47.80%,47.80%,47.80%,50.04%,0.00%,49.38%,54.25%,44.25%,53.42%,55.31%,30.45%,48.67%,48.67%,48.67%,48.67%,48.67%,48.67%,51.03%,0.00%,50.36%,55.33%,45.13%,54.49%,56.41%,2024-07-01 00:00:01,2006-07-27,17.930185
4,5113948,"Fontaine, Liam",D C,07.01.1986,360,20.64%,34.89%,43.62%,34.89%,34.89%,34.89%,34.89%,34.35%,0.00%,34.35%,34.35%,34.35%,34.35%,35.11%,20.64%,35.16%,43.95%,35.16%,35.16%,35.16%,35.16%,34.65%,0.00%,34.65%,34.65%,34.65%,34.65%,35.41%,2024-07-01 00:00:01,1986-01-07,38.480493
5,2002077765,"Musa, David",D LC,19.07.2008,0,21.46%,42.80%,43.45%,34.76%,39.95%,34.76%,34.76%,33.77%,0.00%,36.87%,33.77%,33.77%,35.72%,34.53%,23.98%,46.75%,47.46%,37.97%,43.64%,37.97%,37.97%,36.96%,0.00%,40.35%,36.96%,36.96%,39.10%,37.72%,2024-07-01 00:00:01,2008-07-19,15.950719
6,2002077766,"Watters, Ashley",D L,07.12.2007,0,19.49%,44.41%,42.89%,41.30%,40.30%,35.53%,40.30%,33.62%,0.00%,33.62%,33.62%,33.62%,33.62%,33.62%,21.32%,47.67%,46.04%,44.33%,43.25%,38.13%,43.25%,36.22%,0.00%,36.22%,36.22%,36.22%,36.22%,36.22%,2024-07-01 00:00:01,2007-12-07,16.566735
7,2002077758,"Gwynne, Jamie","D RC, M C",22.02.2008,0,25.17%,33.88%,42.35%,41.54%,33.88%,39.38%,39.38%,32.92%,0.00%,32.92%,32.92%,32.92%,32.92%,33.68%,27.70%,37.14%,46.42%,45.53%,37.14%,43.17%,43.17%,36.24%,0.00%,36.24%,36.24%,36.24%,36.24%,37.00%,2024-07-01 00:00:01,2008-02-22,16.355921
8,2002077759,"Onana, Fabrice","AM R, ST",14.02.2008,0,26.50%,40.83%,40.83%,40.83%,40.83%,40.83%,40.83%,39.44%,0.00%,44.77%,39.44%,39.44%,48.56%,49.30%,30.16%,45.21%,45.21%,45.21%,45.21%,45.21%,45.21%,43.79%,0.00%,49.71%,43.79%,43.79%,53.92%,54.74%,2024-07-01 00:00:01,2008-02-14,16.377823
9,2002077753,"Effiong, Christopher",AM RLC,09.06.2008,0,22.17%,39.45%,39.45%,39.45%,39.45%,39.45%,39.45%,43.53%,0.00%,46.97%,47.19%,47.19%,48.12%,38.49%,24.44%,43.50%,43.50%,43.50%,43.50%,43.50%,43.50%,48.23%,0.00%,52.04%,52.29%,52.29%,53.31%,42.65%,2024-07-01 00:00:01,2008-06-09,16.060233
10,2000134437,"Kovacevic, Alex",GK,09.05.2005,460,59.65%,39.18%,39.18%,39.18%,39.18%,39.18%,39.18%,37.16%,0.00%,37.16%,37.16%,37.16%,37.16%,37.92%,66.81%,44.22%,44.22%,44.22%,44.22%,44.22%,44.22%,41.67%,0.00%,41.67%,41.67%,41.67%,41.67%,42.43%,2024-07-01 00:00:01,2005-05-09,19.145791
11,2002077755,"Dreien, Alexander","AM LC, F C",02.01.2008,0,27.80%,38.82%,38.82%,38.82%,38.82%,38.82%,38.82%,42.80%,0.00%,37.70%,46.43%,46.22%,39.88%,48.08%,34.28%,46.86%,46.86%,46.86%,46.86%,46.86%,46.86%,52.09%,0.00%,45.89%,56.51%,56.26%,48.55%,58.31%,2024-07-01 00:00:01,2008-01-02,16.495551
12,29037157,"McNerney, Joe",D C,24.01.1990,550,15.12%,31.02%,38.77%,36.40%,31.02%,31.02%,31.02%,31.08%,0.00%,31.08%,31.08%,31.08%,31.08%,31.84%,15.12%,31.12%,38.90%,36.52%,31.12%,31.12%,31.12%,31.19%,0.00%,31.19%,31.19%,31.19%,31.19%,31.95%,2024-07-01 00:00:01,1990-01-24,34.433949
13,2002077764,"Cundy-Camper, Luc",D RC,30.10.2007,0,19.68%,32.74%,35.07%,35.60%,28.48%,33.70%,28.48%,28.43%,0.00%,28.43%,28.43%,28.43%,28.43%,28.43%,22.95%,38.07%,40.78%,41.40%,33.12%,39.19%,33.12%,33.13%,0.00%,33.13%,33.13%,33.13%,33.13%,33.13%,2024-07-01 00:00:01,2007-10-30,16.670773
14,2002078880,"Parry, Ian",AM RLC,17.05.2008,0,21.58%,34.62%,34.62%,34.62%,34.62%,34.62%,34.62%,37.54%,0.00%,40.51%,40.70%,40.70%,41.50%,33.96%,24.50%,38.83%,38.83%,38.83%,38.83%,38.83%,38.83%,42.38%,0.00%,45.73%,45.95%,45.95%,46.85%,38.24%,2024-07-01 00:00:01,2008-05-17,16.123203
15,2002077756,"Njoku, Abraham",M RC,09.01.2008,0,19.34%,34.47%,34.47%,34.47%,34.47%,34.47%,34.47%,33.76%,0.00%,41.39%,33.76%,40.25%,38.18%,33.76%,21.86%,38.22%,38.22%,38.22%,38.22%,38.22%,38.22%,37.62%,0.00%,46.12%,37.62%,44.85%,42.54%,37.62%,2024-07-01 00:00:01,2008-01-09,16.476386
16,2000294082,"Woolston, Preston",M C,16.02.2006,0,18.30%,33.82%,33.82%,33.82%,33.82%,40.59%,39.31%,33.31%,0.00%,33.31%,33.31%,33.31%,33.31%,33.31%,23.03%,40.87%,40.87%,40.87%,40.87%,49.05%,47.51%,40.54%,0.00%,40.54%,40.54%,40.54%,40.54%,40.54%,2024-07-01 00:00:01,2006-02-16,18.370979
17,2002077761,"Gall, Paul","WB L, AM LC",08.03.2008,0,24.51%,40.06%,33.18%,33.18%,40.68%,33.18%,33.18%,37.82%,0.00%,32.89%,41.11%,40.32%,32.89%,39.71%,29.21%,48.72%,40.35%,40.35%,49.48%,40.35%,40.35%,46.21%,0.00%,40.18%,50.23%,49.26%,40.18%,48.51%,2024-07-01 00:00:01,2008-03-08,16.314853
18,2002077767,"Spetch, Aarran",WB L,22.09.2007,0,22.14%,38.86%,31.85%,31.85%,39.81%,31.85%,31.85%,30.49%,0.00%,30.49%,32.25%,30.49%,30.49%,30.49%,25.25%,44.90%,36.80%,36.80%,46.00%,36.80%,36.80%,35.50%,0.00%,35.50%,37.56%,35.50%,35.50%,35.50%,2024-07-01 00:00:01,2007-09-22,16.774812
19,2002077754,"Tongue, Stuart","D LC, DM",08.08.2008,0,19.08%,30.60%,31.20%,24.96%,29.02%,24.96%,30.60%,23.91%,0.00%,23.91%,23.91%,23.91%,23.91%,24.67%,23.44%,37.95%,38.70%,30.96%,35.99%,30.96%,37.95%,30.10%,0.00%,30.10%,30.10%,30.10%,30.10%,30.86%,2024-07-01 00:00:01,2008-08-08,15.895962
20,2002077762,"Stapleton, Leo","D RC, M R",12.09.2007,0,12.99%,29.09%,30.82%,31.29%,25.03%,30.22%,25.03%,25.15%,0.00%,30.84%,25.15%,25.15%,28.44%,25.91%,19.18%,39.69%,42.05%,42.68%,34.15%,41.23%,34.15%,34.46%,0.00%,42.24%,34.46%,34.46%,38.96%,35.22%,2024-07-01 00:00:01,2007-09-12,16.802190
21,2002077763,"Harris, Alex","AM RL, ST",18.10.2007,0,15.41%,30.24%,30.24%,30.24%,30.24%,30.24%,30.24%,34.75%,0.00%,34.88%,37.67%,30.73%,37.83%,38.41%,18.03%,33.84%,33.84%,33.84%,33.84%,33.84%,33.84%,38.87%,0.00%,39.02%,42.15%,34.38%,42.33%,42.97%,2024-07-01 00:00:01,2007-10-18,16.703628
22,2002077760,"Alcalá, Aitor","DM, AM C",13.09.2007,0,17.22%,29.44%,29.44%,29.44%,29.44%,29.44%,36.26%,30.24%,0.00%,30.24%,30.24%,37.08%,30.24%,30.24%,24.10%,37.88%,37.88%,37.88%,37.88%,37.88%,46.64%,38.73%,0.00%,38.73%,38.73%,47.48%,38.73%,38.73%,2024-07-01 00:00:01,2007-09-13,16.799452
23,2000110429,"Weeks, Tyler",GK,24.09.2004,200,45.88%,28.14%,28.14%,28.14%,28.14%,28.14%,28.14%,27.28%,0.00%,27.28%,27.28%,27.28%,27.28%,27.28%,56.09%,35.22%,35.22%,35.22%,35.22%,35.22%,35.22%,33.63%,0.00%,33.63%,33.63%,33.63%,33.63%,33.63%,2024-07-01 00:00:01,2004-09-24,19.767283
24,2002077757,"Usman, Victor",DM,13.02.2008,0,19.58%,26.29%,26.29%,26.29%,26.29%,26.29%,32.86%,25.81%,0.00%,30.55%,25.81%,25.81%,28.31%,26.57%,28.29%,38.05%,38.05%,38.05%,38.05%,38.05%,47.56%,37.84%,0.00%,44.77%,37.84%,37.84%,41.49%,38.59%,2024-07-01 00:00:01,2008-02-13,16.380561
25,2002077752,"Cretaro, Sean",GK,14.10.2007,0,48.38%,18.43%,18.43%,18.43%,18.43%,18.43%,18.43%,18.36%,0.00%,18.36%,18.36%,18.36%,18.36%,18.36%,59.59%,27.10%,27.10%,27.10%,27.10%,27.10%,27.10%,26.31%,0.00%,26.31%,26.31%,26.31%,26.31%,26.31%,2024-07-01 00:00:01,2007-10-14,16.714579
26,2002077760,"Alcalá, Aitor","DM, AM C",13.09.2007,50,17.61%,30.93%,30.93%,30.93%,30.93%,30.93%,38.08%,31.47%,0.00%,31.47%,31.47%,38.58%,31.47%,31.47%,24.20%,38.88%,38.88%,38.88%,38.88%,38.88%,47.88%,39.47%,0.00%,39.47%,39.47%,48.39%,39.47%,39.47%,2024-10-01 00:00:01,2007-09-13 00:00:00,17.051335
27,2002077752,"Cretaro, Sean",GK,14.10.2007,0,48.38%,18.34%,18.34%,18.34%,18.34%,18.34%,18.34%,18.28%,0.00%,18.28%,18.28%,18.28%,18.28%,18.28%,59.59%,27.01%,27.01%,27.01%,27.01%,27.01%,27.01%,26.22%,0.00%,26.22%,26.22%,26.22%,26.22%,26.22%,2024-10-01 00:00:01,2007-10-14 00:00:00,16.966461
28,2002077764,"Cundy-Camper, Luc",D RC,30.10.2007,0,20.08%,34.74%,37.22%,37.78%,30.23%,35.77%,30.23%,29.89%,0.00%,29.89%,29.89%,29.89%,29.89%,29.89%,23.00%,40.08%,42.93%,43.58%,34.86%,41.26%,34.86%,34.59%,0.00%,34.59%,34.59%,34.59%,34.59%,34.59%,2024-10-01 00:00:01,2007-10-30 00:00:00,16.922656
29,2002077755,"Dreien, Alexander","AM LC, F C",02.01.2008,0,27.91%,39.37%,39.37%,39.37%,39.37%,39.37%,39.37%,43.39%,0.00%,38.23%,47.07%,47.07%,40.44%,48.73%,34.10%,47.29%,47.29%,47.29%,47.29%,47.29%,47.29%,52.50%,0.00%,46.26%,56.96%,56.96%,48.93%,58.77%,2024-10-01 00:00:01,2008-01-02 00:00:00,16.747433
30,2002077753,"Effiong, Christopher",AM RLC,09.06.2008,0,22.55%,39.70%,39.70%,39.70%,39.70%,39.70%,39.70%,43.78%,0.00%,47.25%,47.47%,47.68%,48.40%,38.72%,24.82%,43.69%,43.69%,43.69%,43.69%,43.69%,43.69%,48.42%,0.00%,52.25%,52.49%,52.72%,53.52%,42.82%,2024-10-01 00:00:01,2008-06-09 00:00:00,16.312115
31,5113948,"Fontaine, Liam",D C,07.01.1986,360,19.78%,33.80%,42.25%,33.80%,33.80%,33.80%,33.80%,33.21%,0.00%,33.21%,33.21%,33.21%,33.21%,33.97%,19.78%,34.07%,42.59%,34.07%,34.07%,34.07%,34.07%,33.51%,0.00%,33.51%,33.51%,33.51%,33.51%,34.27%,2024-10-01 00:00:01,1986-01-07 00:00:00,38.732375
32,2002077761,"Gall, Paul","WB L, AM LC",08.03.2008,0,24.49%,40.68%,33.69%,33.69%,41.49%,33.69%,33.69%,38.21%,0.00%,33.23%,41.53%,40.91%,33.23%,40.12%,29.18%,49.34%,40.87%,40.87%,50.32%,40.87%,40.87%,46.60%,0.00%,40.52%,50.65%,49.89%,40.52%,48.92%,2024-10-01 00:00:01,2008-03-08 00:00:00,16.566735
33,2002077758,"Gwynne, Jamie","D RC, DM",22.02.2008,0,25.19%,34.69%,43.36%,42.52%,34.69%,40.32%,42.71%,33.48%,0.00%,33.48%,33.48%,33.48%,33.48%,34.24%,27.32%,37.45%,46.81%,45.91%,37.45%,43.53%,46.11%,36.27%,0.00%,36.27%,36.27%,36.27%,36.27%,37.02%,2024-10-01 00:00:01,2008-02-22 00:00:00,16.607803
34,2002077763,"Harris, Alex","AM RL, ST",18.10.2007,0,15.61%,30.81%,30.81%,30.81%,30.81%,30.81%,30.81%,35.35%,0.00%,35.48%,38.32%,31.26%,38.49%,39.07%,18.13%,34.19%,34.19%,34.19%,34.19%,34.19%,34.19%,39.22%,0.00%,39.37%,42.52%,34.69%,42.71%,43.36%,2024-10-01 00:00:01,2007-10-18 00:00:00,16.955510
35,2000134437,"Kovacevic, Alex",GK,09.05.2005,460,59.90%,39.01%,39.01%,39.01%,39.01%,39.01%,39.01%,36.98%,0.00%,36.98%,36.98%,36.98%,36.98%,37.73%,67.06%,44.07%,44.07%,44.07%,44.07%,44.07%,44.07%,41.52%,0.00%,41.52%,41.52%,41.52%,41.52%,42.27%,2024-10-01 00:00:01,2005-05-09 00:00:00,19.397673
36,29037157,"McNerney, Joe",D C,24.01.1990,550,14.56%,30.21%,37.76%,35.45%,30.21%,30.21%,30.21%,30.37%,0.00%,30.37%,30.37%,30.37%,30.37%,31.13%,14.56%,30.31%,37.89%,35.57%,30.31%,30.31%,30.31%,30.48%,0.00%,30.48%,30.48%,30.48%,30.48%,31.23%,2024-10-01 00:00:01,1990-01-24 00:00:00,34.685832
37,2002077765,"Musa, David",D LC,19.07.2008,0,21.75%,44.23%,44.90%,35.92%,41.29%,35.92%,35.92%,34.70%,0.00%,37.89%,34.70%,34.70%,36.71%,35.46%,24.27%,48.18%,48.91%,39.13%,44.98%,39.13%,39.13%,37.90%,0.00%,41.37%,37.90%,37.90%,40.09%,38.66%,2024-10-01 00:00:01,2008-07-19 00:00:00,16.202601
38,2002077756,"Njoku, Abraham",AM RC,09.01.2008,0,19.81%,35.77%,35.77%,35.77%,35.77%,35.77%,35.77%,34.89%,0.00%,42.77%,34.89%,42.96%,39.45%,34.89%,22.33%,39.52%,39.52%,39.52%,39.52%,39.52%,39.52%,38.75%,0.00%,47.51%,38.75%,47.71%,43.82%,38.75%,2024-10-01 00:00:01,2008-01-09 00:00:00,16.728268
39,2000231345,"Odei-Larbi, Joel","AM L, ST",27.07.2006,40,29.37%,47.91%,47.91%,47.91%,47.91%,47.91%,47.91%,50.25%,0.00%,49.40%,54.51%,44.27%,53.45%,55.34%,30.06%,48.77%,48.77%,48.77%,48.77%,48.77%,48.77%,51.25%,0.00%,50.39%,55.60%,45.15%,54.52%,56.44%,2024-10-01 00:00:01,2006-07-27 00:00:00,18.182067
40,2002077759,"Onana, Fabrice","AM R, ST",14.02.2008,0,26.57%,41.40%,41.40%,41.40%,41.40%,41.40%,41.40%,39.83%,0.00%,45.21%,39.83%,39.83%,49.05%,49.79%,29.84%,45.15%,45.15%,45.15%,45.15%,45.15%,45.15%,43.60%,0.00%,49.49%,43.60%,43.60%,53.68%,54.50%,2024-10-01 00:00:01,2008-02-14 00:00:00,16.629706
41,2002078880,"Parry, Ian",AM RLC,17.05.2008,0,21.58%,35.04%,35.04%,35.04%,35.04%,35.04%,35.04%,37.89%,0.00%,40.88%,41.08%,41.25%,41.88%,34.26%,24.50%,39.02%,39.02%,39.02%,39.02%,39.02%,39.02%,42.51%,0.00%,45.87%,46.09%,46.29%,46.99%,38.35%,2024-10-01 00:00:01,2008-05-17 00:00:00,16.375086
42,2002077767,"Spetch, Aarran",WB L,22.09.2007,20,21.85%,39.20%,32.13%,32.13%,40.16%,35.84%,32.13%,30.58%,0.00%,30.58%,32.35%,30.58%,30.58%,30.58%,24.96%,45.24%,37.08%,37.08%,46.35%,41.37%,37.08%,35.59%,0.00%,35.59%,37.65%,35.59%,35.59%,35.59%,2024-10-01 00:00:01,2007-09-22 00:00:00,17.026694
43,2002077762,"Stapleton, Leo","D RC, M R",12.09.2007,0,13.56%,31.15%,32.99%,33.49%,26.79%,32.99%,26.79%,26.57%,0.00%,32.57%,26.57%,26.57%,30.04%,27.33%,19.75%,41.74%,44.22%,44.89%,35.91%,44.22%,35.91%,35.87%,0.00%,43.98%,35.87%,35.87%,40.57%,36.63%,2024-10-01 00:00:01,2007-09-12 00:00:00,17.054073
44,2002077754,"Tongue, Stuart","D LC, DM",08.08.2008,0,19.47%,32.41%,33.05%,26.44%,30.73%,26.44%,32.56%,25.16%,0.00%,25.16%,25.16%,25.16%,25.16%,25.92%,23.83%,39.52%,40.29%,32.24%,37.47%,32.24%,39.69%,31.09%,0.00%,31.09%,31.09%,31.09%,31.09%,31.85%,2024-10-01 00:00:01,2008-08-08 00:00:00,16.147844
45,2002077757,"Usman, Victor",DM,13.02.2008,0,19.77%,27.06%,27.06%,27.06%,27.06%,27.06%,33.83%,26.43%,0.00%,31.28%,26.43%,26.43%,28.99%,27.19%,28.19%,38.72%,38.72%,38.72%,38.72%,38.72%,48.41%,38.32%,0.00%,45.35%,38.32%,38.32%,42.03%,39.08%,2024-10-01 00:00:01,2008-02-13 00:00:00,16.632444
46,2002077766,"Watters, Ashley",D LC,07.12.2007,0,19.78%,45.43%,44.75%,42.25%,41.23%,36.34%,41.23%,34.25%,0.00%,34.25%,34.25%,34.25%,34.25%,34.25%,21.22%,47.94%,47.23%,44.58%,43.50%,38.35%,43.50%,36.31%,0.00%,36.31%,36.31%,36.31%,36.31%,36.31%,2024-10-01 00:00:01,2007-12-07 00:00:00,16.818617
47,2000110429,"Weeks, Tyler",GK,24.09.2004,200,46.21%,28.02%,28.02%,28.02%,28.02%,28.02%,28.02%,27.16%,0.00%,27.16%,27.16%,27.16%,27.16%,27.16%,56.42%,35.13%,35.13%,35.13%,35.13%,35.13%,35.13%,33.53%,0.00%,33.53%,33.53%,33.53%,33.53%,33.53%,2024-10-01 00:00:01,2004-09-24 00:00:00,20.019165
48,2000138022,"Willson, Brendan",D C,01.07.2003,190,23.18%,40.64%,50.80%,40.64%,40.64%,40.64%,44.37%,38.00%,0.00%,38.00%,38.00%,38.00%,38.00%,38.00%,23.47%,40.96%,51.20%,40.96%,40.96%,40.96%,44.72%,38.27%,0.00%,38.27%,38.27%,38.27%,38.27%,38.27%,2024-10-01 00:00:01,2003-07-01 00:00:00,21.253936
49,29192118,"Woollard-Innocent, Kai",D/WB L,28.09.2000,490,27.33%,53.03%,48.77%,42.43%,52.85%,46.32%,42.43%,40.78%,0.00%,40.78%,40.78%,40.78%,40.78%,40.78%,30.60%,58.24%,53.56%,46.59%,58.04%,50.87%,46.59%,44.98%,0.00%,44.98%,44.98%,44.98%,44.98%,44.98%,2024-10-01 00:00:01,2000-09-28 00:00:00,24.008214
50,2000294082,"Woolston, Preston",M C,16.02.2006,20,18.30%,34.02%,34.02%,34.02%,34.02%,41.52%,39.55%,33.47%,0.00%,33.47%,33.47%,33.47%,33.47%,33.47%,23.03%,41.07%,41.07%,41.07%,41.07%,50.12%,47.75%,40.71%,0.00%,40.71%,40.71%,40.71%,40.71%,40.71%,2024-10-01 00:00:01,2006-02-16 00:00:00,18.622861
51,2000134437,"Kovacevic, Alex",GK,09.05.2005,460,59.90%,39.01%,39.01%,39.01%,39.01%,39.01%,39.01%,36.98%,0.00%,36.98%,36.98%,36.98%,36.98%,37.73%,67.06%,44.07%,44.07%,44.07%,44.07%,44.07%,44.07%,41.52%,0.00%,41.52%,41.52%,41.52%,41.52%,42.27%,2024-10-01 00:00:01,2005-05-09 00:00:00,19.397673
52,2000231345,"Odei-Larbi, Joel","AM L, ST",27.07.2006,40,29.38%,47.99%,47.99%,47.99%,47.99%,47.99%,47.99%,50.35%,0.00%,49.50%,54.62%,44.36%,53.56%,55.45%,30.07%,48.86%,48.86%,48.86%,48.86%,48.86%,48.86%,51.35%,0.00%,50.49%,55.71%,45.24%,54.62%,56.55%,2025-01-01 00:00:01,2006-07-27 00:00:00,18.433949
53,2002077758,"Gwynne, Jamie","D RC, DM",22.02.2008,0,25.53%,36.28%,45.35%,44.48%,36.28%,42.17%,45.35%,34.83%,0.00%,34.83%,34.83%,34.83%,34.83%,35.59%,27.36%,38.63%,48.29%,47.36%,38.63%,44.90%,48.29%,37.21%,0.00%,37.21%,37.21%,37.21%,37.21%,37.97%,2025-01-01 00:00:01,2008-02-22 00:00:00,16.859685
54,2000138022,"Willson, Brendan",D C,01.07.2003,190,23.18%,40.85%,51.06%,40.85%,40.85%,40.85%,44.60%,38.18%,0.00%,38.18%,38.18%,38.18%,38.18%,38.18%,23.47%,40.97%,51.21%,40.97%,40.97%,40.97%,44.72%,38.28%,0.00%,38.28%,38.28%,38.28%,38.28%,38.28%,2025-01-01 00:00:01,2003-07-01 00:00:00,21.505818
55,29192118,"Woollard-Innocent, Kai",D/WB L,28.09.2000,490,27.70%,54.19%,49.83%,43.35%,54.00%,48.37%,43.35%,41.62%,0.00%,41.62%,41.62%,41.62%,41.62%,41.62%,30.97%,59.39%,54.62%,47.52%,59.19%,53.01%,47.52%,45.82%,0.00%,45.82%,45.82%,45.82%,45.82%,45.82%,2025-01-01 00:00:01,2000-09-28 00:00:00,24.260096
56,2002077759,"Onana, Fabrice","AM R, ST",14.02.2008,0,26.95%,42.30%,42.30%,42.30%,42.30%,42.30%,42.30%,40.64%,0.00%,46.13%,40.64%,40.64%,50.04%,50.79%,29.87%,46.05%,46.05%,46.05%,46.05%,46.05%,46.05%,44.40%,0.00%,50.40%,44.40%,44.40%,54.68%,55.50%,2025-01-01 00:00:01,2008-02-14 00:00:00,16.881588
57,2002077766,"Watters, Ashley",D LC,07.12.2007,0,19.88%,46.29%,45.60%,43.04%,42.00%,37.03%,42.00%,34.80%,0.00%,34.80%,34.80%,34.80%,34.80%,34.80%,21.60%,49.28%,48.54%,45.82%,44.72%,39.42%,44.72%,37.22%,0.00%,37.22%,37.22%,37.22%,37.22%,37.22%,2025-01-01 00:00:01,2007-12-07 00:00:00,17.070500
58,2002077760,"Alcalá, Aitor","DM, AM C",13.09.2007,60,18.11%,33.50%,33.50%,33.50%,33.50%,33.50%,41.87%,33.60%,0.00%,33.60%,33.60%,41.19%,33.60%,33.60%,24.30%,40.73%,40.73%,40.73%,40.73%,40.73%,50.92%,40.88%,0.00%,40.88%,40.88%,50.12%,40.88%,40.88%,2025-01-01 00:00:01,2007-09-13 00:00:00,17.303217
59,2000294082,"Woolston, Preston","WB R, M C",16.02.2006,20,18.42%,35.92%,35.92%,35.92%,35.92%,44.04%,41.76%,35.00%,0.00%,35.00%,35.00%,35.00%,35.00%,35.00%,22.77%,42.32%,42.32%,42.32%,42.32%,51.88%,49.19%,41.58%,0.00%,41.58%,41.58%,41.58%,41.58%,41.58%,2025-01-01 00:00:01,2006-02-16 00:00:00,18.874743
60,2002077755,"Dreien, Alexander","AM LC, F C",02.01.2008,0,28.02%,40.90%,40.90%,40.90%,40.90%,40.90%,40.90%,44.89%,0.00%,39.55%,48.70%,49.44%,41.84%,50.38%,33.82%,48.05%,48.05%,48.05%,48.05%,48.05%,48.05%,53.11%,0.00%,46.79%,57.62%,58.49%,49.50%,59.44%,2025-01-01 00:00:01,2008-01-02 00:00:00,16.999316
61,2002077753,"Effiong, Christopher",AM RLC,09.06.2008,0,22.93%,40.76%,40.76%,40.76%,40.76%,40.76%,40.76%,44.75%,0.00%,48.29%,48.51%,48.73%,49.46%,39.57%,25.19%,44.76%,44.76%,44.76%,44.76%,44.76%,44.76%,49.38%,0.00%,53.29%,53.54%,53.77%,54.59%,43.67%,2025-01-01 00:00:01,2008-06-09 00:00:00,16.563997
62,2000134437,"Kovacevic, Alex",GK,09.05.2005,460,59.93%,39.20%,39.20%,39.20%,39.20%,39.20%,39.20%,37.16%,0.00%,37.16%,37.16%,37.16%,37.16%,37.92%,67.09%,44.31%,44.31%,44.31%,44.31%,44.31%,44.31%,41.75%,0.00%,41.75%,41.75%,41.75%,41.75%,42.51%,2025-01-01 00:00:01,2005-05-09 00:00:00,19.649555
63,2002077765,"Musa, David",D LC,19.07.2008,0,22.04%,45.71%,46.41%,37.12%,42.67%,37.12%,37.12%,35.74%,0.00%,39.02%,35.74%,35.74%,37.81%,36.50%,24.27%,49.40%,50.14%,40.11%,46.11%,40.11%,40.11%,38.70%,0.00%,42.25%,38.70%,38.70%,40.94%,39.46%,2025-01-01 00:00:01,2008-07-19 00:00:00,16.454483
64,2002077756,"Njoku, Abraham",AM RC,09.01.2008,0,19.63%,37.02%,37.02%,37.02%,37.02%,37.02%,37.02%,35.92%,0.00%,44.04%,35.92%,44.23%,40.62%,35.92%,21.86%,40.62%,40.62%,40.62%,40.62%,40.62%,40.62%,39.61%,0.00%,48.56%,39.61%,48.77%,44.79%,39.61%,2025-01-01 00:00:01,2008-01-09 00:00:00,16.980151
65,2002078880,"Parry, Ian",AM RLC,17.05.2008,0,21.78%,35.47%,35.47%,35.47%,35.47%,35.47%,35.47%,38.23%,0.00%,41.25%,41.45%,41.63%,42.26%,34.56%,24.40%,39.34%,39.34%,39.34%,39.34%,39.34%,39.34%,42.72%,0.00%,46.09%,46.31%,46.51%,47.22%,38.53%,2025-01-01 00:00:01,2008-05-17 00:00:00,16.626968

In [6]:
import re


# 2. Convert percentages to float
def convert_percent(val):
    if isinstance(val, str) and '%' in val:
        try:
            return round(float(val.replace('%', '')), 2)
        except ValueError:
            return val
    return val

all_players_table = all_players_table.applymap(convert_percent)

# 3. Round floats to 2 decimal places
all_players_table = all_players_table.applymap(lambda x: round(x, 2) if isinstance(x, float) else x)

# 4. Convert date columns to datetime
date_cols = [col for col in all_players_table.columns if 'date' in col or 'dob' in col]
for col in date_cols:
    all_players_table[col] = pd.to_datetime(all_players_table[col], errors='coerce')

C:\Users\jackj\AppData\Local\Temp\ipykernel_25580\3599946538.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  all_players_table = all_players_table.applymap(convert_percent)
C:\Users\jackj\AppData\Local\Temp\ipykernel_25580\3599946538.py:16: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  all_players_table = all_players_table.applymap(lambda x: round(x, 2) if isinstance(x, float) else x)

In [7]:
all_players_table['DoB'] = pd.to_datetime(all_players_table['DoB'], dayfirst=True, errors='coerce')
all_players_table['Date'] = pd.to_datetime(all_players_table['Date'], errors='coerce')


# Define a function to get Jan 1st of the football season
def get_season_jan1(date):
    if pd.isna(date):
        return pd.NaT
    return pd.Timestamp(year=date.year if date.month < 7 else date.year + 1, month=1, day=1)

# Create the 'Season Jan 1' date
all_players_table['Season Jan 1'] = all_players_table['Date'].apply(get_season_jan1)

# Calculate age on Jan 1 of the season
all_players_table['Age as of Jan 1'] = (
    all_players_table['Season Jan 1'].dt.year - all_players_table['DoB'].dt.year
    - all_players_table.apply(
        lambda row: (row['Season Jan 1'].month, row['Season Jan 1'].day) < (row['DoB'].month, row['DoB'].day),
        axis=1
    )
)

In [8]:
latest_export_date = all_players_table['Date'].max()
earliest_ratings = all_players_table.loc[all_players_table.groupby('Unique ID')['Date'].idxmin(), ['Unique ID', 'GK Rating','FS Rating']].rename(columns={'GK Rating': 'First GK Rating','FS Rating': 'First FS Rating'})
all_players_table = all_players_table.merge(earliest_ratings, on='Unique ID', how='left')
all_players_table['GK Growth'] = all_players_table['GK Rating'] - all_players_table['First GK Rating']
all_players_table['FS Growth'] = all_players_table['FS Rating'] - all_players_table['First FS Rating']

all_players_table['is_latest_export'] = all_players_table['Date'] == latest_export_date
df_max_date = all_players_table[all_players_table['Date'] == latest_export_date]
df_max_date['in_latest_export'] = True
all_players_table = pd.merge(all_players_table, df_max_date, how="left", on=["Unique ID"],suffixes = [None,'_current'])
all_players_table=all_players_table.round(2)

C:\Users\jackj\AppData\Local\Temp\ipykernel_25580\3608406180.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_max_date['in_latest_export'] = True

In [9]:
all_players_table

,Unique ID,Name,Position,Date Of Birth,Wage,GK Rating,DL Rating,DC Rating,DR Rating,WBL Rating,WBR Rating,DM Rating,ML Rating,MC Rating,MR Rating,AML Rating,AMC Rating,AMR Rating,FS Rating,GK Pot Rating,DL Pot Rating,DC Pot Rating,DR Pot Rating,WBL Pot Rating,WBR Pot Rating,DM Pot Rating,ML Pot Rating,MC Pot Rating,MR Pot Rating,AML Pot Rating,AMC Pot Rating,...,MC Rating_current,MR Rating_current,AML Rating_current,AMC Rating_current,AMR Rating_current,FS Rating_current,GK Pot Rating_current,DL Pot Rating_current,DC Pot Rating_current,DR Pot Rating_current,WBL Pot Rating_current,WBR Pot Rating_current,DM Pot Rating_current,ML Pot Rating_current,MC Pot Rating_current,MR Pot Rating_current,AML Pot Rating_current,AMC Pot Rating_current,AMR Pot Rating_current,FS Pot Rating_current,Date_current,DoB_current,Age_current,Season Jan 1_current,Age as of Jan 1_current,First GK Rating_current,First FS Rating_current,GK Growth_current,FS Growth_current,is_latest_export_current,in_latest_export
0,2000138022,"Willson, Brendan",D C,01.07.2003,190,23.19,40.51,50.63,40.51,40.51,40.51,44.22,37.97,0.0,37.97,37.97,37.97,37.97,37.97,23.49,40.89,51.11,40.89,40.89,40.89,44.64,38.30,0.0,38.30,38.30,38.30,...,0.0,38.18,38.18,38.18,38.18,38.18,23.47,40.97,51.21,40.97,40.97,40.97,44.72,38.28,0.0,38.28,38.28,38.28,38.28,38.28,2025-01-01 00:00:01,NaT,21.51,2025-01-01,NaN,23.19,37.97,-0.01,0.21,True,True
1,43273316,"Faal, Muhammadu","AM RL, ST",01.07.1997,850,33.31,50.16,50.16,50.16,50.16,50.16,50.16,55.65,0.0,55.05,60.43,48.69,59.69,61.81,35.53,53.37,53.37,53.37,53.37,53.37,53.37,59.34,0.0,58.71,64.45,51.92,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,29192118,"Woollard-Innocent, Kai",D/WB L,28.09.2000,490,27.24,52.89,48.64,42.31,52.71,42.31,42.31,40.72,0.0,40.72,40.72,40.72,40.72,40.72,30.51,58.10,53.43,46.48,57.90,46.48,46.48,44.93,0.0,44.93,44.93,44.93,...,0.0,41.62,41.62,41.62,41.62,41.62,30.97,59.39,54.62,47.52,59.19,53.01,47.52,45.82,0.0,45.82,45.82,45.82,45.82,45.82,2025-01-01 00:00:01,NaT,24.26,2025-01-01,NaN,27.24,40.72,0.46,0.90,True,True
3,2000231345,"Odei-Larbi, Joel","AM L, ST",27.07.2006,0,29.76,47.80,47.80,47.80,47.80,47.80,47.80,50.04,0.0,49.38,54.25,44.25,53.42,55.31,30.45,48.67,48.67,48.67,48.67,48.67,48.67,51.03,0.0,50.36,55.33,45.13,...,0.0,49.50,54.62,44.36,53.56,55.45,30.07,48.86,48.86,48.86,48.86,48.86,48.86,51.35,0.0,50.49,55.71,45.24,54.62,56.55,2025-01-01 00:00:01,NaT,18.43,2025-01-01,NaN,29.76,55.31,-0.38,0.14,True,True
4,5113948,"Fontaine, Liam",D C,07.01.1986,360,20.64,34.89,43.62,34.89,34.89,34.89,34.89,34.35,0.0,34.35,34.35,34.35,34.35,35.11,20.64,35.16,43.95,35.16,35.16,35.16,35.16,34.65,0.0,34.65,34.65,34.65,...,0.0,32.28,32.28,32.28,32.28,33.04,19.50,33.09,41.36,33.09,33.09,33.09,33.09,32.58,0.0,32.58,32.58,32.58,32.58,33.34,2025-01-01 00:00:01,NaT,38.98,2025-01-01,NaN,20.64,35.11,-1.14,-2.07,True,True
5,2002077765,"Musa, David",D LC,19.07.2008,0,21.46,42.80,43.45,34.76,39.95,34.76,34.76,33.77,0.0,36.87,33.77,33.77,35.72,34.53,23.98,46.75,47.46,37.97,43.64,37.97,37.97,36.96,0.0,40.35,36.96,36.96,...,0.0,39.02,35.74,35.74,37.81,36.50,24.27,49.40,50.14,40.11,46.11,40.11,40.11,38.70,0.0,42.25,38.70,38.70,40.94,39.46,2025-01-01 00:00:01,NaT,16.45,2025-01-01,NaN,21.46,34.53,0.58,1.97,True,True
6,2002077766,"Watters, Ashley",D L,07.12.2007,0,19.49,44.41,42.89,41.30,40.30,35.53,40.30,33.62,0.0,33.62,33.62,33.62,33.62,33.62,21.32,47.67,46.04,44.33,43.25,38.13,43.25,36.22,0.0,36.22,36.22,36.22,...,0.0,34.80,34.80,34.80,34.80,34.80,21.60,49.28,48.54,45.82,44.72,39.42,44.72,37.22,0.0,37.22,37.22,37.22,37.22,37.22,2025-01-01 00:00:01,NaT,17.07,2025-01-01,NaN,19.49,33.62,0.39,1.18,True,True
7,2002077758,"Gwynne, Jamie","D RC, M C",22.02.2008,0,25.17,33.88,42.35,41.54,33.88,39.38,39.38,32.92,0.0,32.92,32.92,32.92,32.92,33.68,27.70,37.14,46.42,45.53,37.14,43.17,43.17,36.24,0.0,36.24,36.24,36.24,...,0.0,34.83,34.83,34.83,34.83,35.59,27.36,38.63,48.29,47.36,38.63,44.90,48.29,37.21,0.0,37.21,37.21,37.21,37.21,37.97,2025-01-01 00:00:01,NaT,16.86,2025-01-01,NaN,25.17,33.68,0.36,1.91,True,True
8,2002077759,"Onana, Fabrice","AM R, ST",14.02.2008,0,26.50,40.83,40.83,40.83,40.83,40.83,40.83,39.44,0.0,44.77,39.44,39.44,48.56,49.30,30.16,45.21,45.21,45.21,45.21,45.21,45.21,43.79,0.0,49.71,43.79,43.79,...,0.0,46.13,40.64,40.64,50.04,50.79,29.87,46.05,46.05,46.05,46.05,46.05,46.05,44.40,0.0,50.40,44.40,44.40,54.68,55.50,2025-01-01 00:00:01,NaT,16.88,2025-01-01,NaN,26.50,49.30,0.45,1.49,True,True
9,2002077753,"Effiong, Christopher",AM RLC,09.06.2008,0,22.17,39.45,39.45,39.45,39.45,39.45,39.45,43.53,0.0,46.97,47.19,47.19,48.12,38.49,24.44,43.50,43.50,43.50,43.50,43.50,43.50,48.23,0.0,52.04,52.29,52.29,...,0.0,48.29,48.51,48.73,49.46,39.57,25.19,44.76,44.76,44.76,44.76,44.76,44.76,49.38,0.0,53.29,53.54,53.77,54.59,43.67,2025-01-01 00:00:01,NaT,16.56,2025-01-01,NaN,22.17,38.49,0.76,1.08,True,True
10,2000134437,"Kovacevic, Alex",GK,09.05.2005,460,59.65,39.18,39.18,39.18,39.18,39.18,39.18,37.16,0.0,37.16,37.16,37.16,37.16,37.92,66.81,44.22,44.22,44.22,44.22,44.22,44.22,41.67,0.0,41.67,41.67,41.67,...,0.0,37.16,37.16,37.16,37.16,37.92,67.09,44.31,44.31,44.31,44.31,44.31,44.31,41.75,0.0,41.75,41.75,41.75,41.75,42.51,2025-01-01 00:00:01,NaT,19.65,2025-01-01,NaN,59.65,37.92,0.28,0.00,True,True
11,2002077755,"Dreien, Alexander","AM LC, F C",02.01.2008,0,27.80,38.82,38.82,38.82,38.82,38.82,38.82,42.80,0.0,37.70,46.43,46.22,39.88,48.08,34.28,46.86,46.86,46.86,46.86,46.86,46.86,52.09,0.0,45.89,56.51,56.26,...,0.0,39.55,48.70,49.44,41.84,50.38,33.82,48.05,48.05,48.05,48.05,48.05,48.05,53.11,0.0,46.79,57.62,58.49,49.50,59.44,2025-01-01 00:00:01,NaT,17.00,2025-01-01,NaN,27.80,48.08,0.22,2.30,True,True
12,29037157,"McNerney, Joe",D C,24.01.1990,550,15.12,31.02,38.77,36.40,31.02,31.02,31.02,31.08,0.0,31.08,31.08,31.08,31.08,31.84,15.12,31.12,38.90,36.52,31.12,31.12,31.12,31.19,0.0,31.19,31.19,31.19,...,0.0,29.47,29.47,29.47,29.47,30.23,14.44,29.39,36.74,34.49,29.39,29.39,29.39,29.58,0.0,29.58,29.58,29.58,29.58,30.34,2025-01-01 00:00:01,NaT,34.94,2025-01-01,NaN,15.12,31.84,-0.68,-1.61,True,True
13,2002077764,"Cundy-Camper, Luc",D RC,30.10.2007,0,19.68,32.74,35.07,35.60,28.48,33.70,28.48,28.43,0.0,28.43,28.43,28.43,28.43,28.43,22.95,38.07,40.78,41.40,33.12,39.19,33.12,33.13,0.0,33.13,33.13,33.13,...,0.0,29.94,29.94,29.94,29.94,29.94,22.80,40.31,43.18,43.84,35.07,41.50,35.07,34.64,0.0,34.64,34.64,34.64,34.64,34.64,2025-01-01 00:00:01,NaT,17.17,2025-01-01,NaN,19.68,28.43,0.20,1.51,True,True
14,2002078880,"Parry, Ian",AM RLC,17.05.2008,0,21.58,34.62,34.62,34.62,34.62,34.62,34.62,37.54,0.0,40.51,40.70,40.70,41.50,33.96,24.50,38.83,38.83,38.83,38.83,38.83,38.83,42.38,0.0,45.73,45.95,45.95,...,0.0,41.25,41.45,41.63,42.26,34.56,24.40,39.34,39.34,39.34,39.34,39.34,39.34,42.72,0.0,46.09,46.31,46.51,47.22,38.53,2025-01-01 00:00:01,NaT,16.63,2025-01-01,NaN,21.58,33.96,0.20,0.60,True,True
15,2002077756,"Njoku, Abraham",M RC,09.01.2008,0,19.34,34.47,34.47,34.47,34.47,34.47,34.47,33.76,0.0,41.39,33.76,40.25,38.18,33.76,21.86,38.22,38.22,38.22,38.22,38.22,38.22,37.62,0.0,46.12,37.62,44.85,...,0.0,44.04,35.92,44.23,40.62,35.92,21.86,40.62,40.62,40.62,40.62,40.62,40.62,39.61,0.0,48.56,39.61,48.77,44.79,39.61,2025-01-01 00:00:01,NaT,16.98,2025-01-01,NaN,19.34,33.76,0.29,2.16,True,True
16,2000294082,"Woolston, Preston",M C,16.02.2006,0,18.30,33.82,33.82,33.82,33.82,40.59,39.31,33.31,0.0,33.31,33.31,33.31,33.31,33.31,23.03,40.87,40.87,40.87,40.87,49.05,47.51,40.54,0.0,40.54,40.54,40.54,...,0.0,35.00,35.00,35.00,35.00,35.00,22.77,42.32,42.32,42.32,42.32,51.88,49.19,41.58,0.0,41.58,41.58,41.58,41.58,41.58,2025-01-01 00:00:01,NaT,18.87,2025-01-01,NaN,18.30,33.31,0.12,1.69,True,True
17,2002077761,"Gall, Paul","WB L, AM LC",08.03.2008,0,24.51,40.06,33.18,33.18,40.68,33.18,33.18,37.82,0.0,32.89,41.11,40.32,32.89,39.71,29.21,48.72,40.35,40.35,49.48,40.35,40.35,46.21,0.0,40.18,50.23,49.26,...,0.0,33.97,42.46,41.82,33.97,41.01,29.18,50.37,41.72,41.72,51.37,41.72,41.72,47.44,0.0,41.25,51.56,50.80,41.25,49.81,2025-01-01 00:00:01,NaT,16.82,2025-01-01,NaN,24.51,39.71,-0.02,1.30,True,True
18,2002077767,"Spetch, Aarran",WB L,22.09.2007,0,22.14,38.86,31.85,31.85,39.81,31.85,31.85,30.49,0.0,30.49,32.25,30.49,30.49,30.49,25.25,44.90,36.80,36.80,46.00,36.80,36.80,35.50,0.0,35.50,37.56,35.50,...,0.0,30.89,32.68,30.89,30.89,30.89,25.61,46.13,37.46,37.46,46.83,41.79,37.46,35.96,0.0,35.96,38.04,35.96,35.96,35.96,2025-01-01 00:00:01,NaT,17.28,2025-01-01,NaN,22.14,30.49,-0.19,0.40,True,True
19,2002077754,"Tongue, Stuart","D LC, DM",08.08.2008,0,19.08,30.60,31.20,24.96,29.02,24.96,30.60,23.91,0.0,23.91,23.91,23.91,23.91,24.67,23.44,37.95,38.70,30.96,35.99,30.96,37.95,30.10,0.0,30.10,30.10,30.10,...,0.0,25.66,25.66,25.66,25.66,26.42,23.83,40.40,41.19,32.95,38.30,32.95,40.57,31.59,0.0,31.59,31.59,31.59,31.59,32.35,2025-01-01 00:00:01,NaT,16.40,2025-01-01,NaN,19.08,24.67,0.40,1.75,True,True
20,2002077762,"Stapleton, Leo","D RC, M R",12.09.2007,0,12.99,29.09,30.82,31.29,25.03,30.22,25.03,25.15,0.0,30.84,25.15,25.15,28.44,25.91,19.18,39.69,42.05,42.68,34.15,41.23,34.15,34.46,0.0,42.24,34.46,34.46,...,0.0,34.25,27.93,27.93,31.59,28.69,19.56,42.48,45.00,45.68,36.54,45.00,36.54,36.30,0.0,44.51,36.30,36.30,41.05,37.06,2025-01-01 00:00:01,NaT,17.31,2025-01-01,NaN,12.99,25.91,1.08,2.78,True,True
21,2002077763,"Harris, Alex","AM RL, ST",18.10.2007,0,15.41,30.24,30.24,30.24,30.24,30.24,30.24,34.75,0.0,34.88,37.67,30.73,37.83,38.41,18.03,33.84,33.84,33.84,33.84,33.84,33.84,38.87,0.0,39.02,42.15,34.38,...,0.0,35.71,38.57,31.46,38.74,39.33,18.23,34.41,34.41,34.41,34.41,34.41,34.41,39.45,0.0,39.60,42.77,34.89,42.96,43.61,2025-01-01 00:00:01,NaT,17.21,2025-01-01,NaN,15.41,38.41,0.30,0.92,True,True
22,2002077760,"Alcalá, Aitor","DM, AM C",13.09.2007,0,17.22,29.44,29.44,29.44,29.44,29.44,36.26,30.24,0.0,30.24,30.24,37.08,30.24,30.24,24.10,37.88,37.88,37.88,37.88,37.88,46.64,38.73,0.0,38.73,38.73,47.48,...,0.0,33.60,33.60,41.19,33.60,33.60,24.30,40.73,40.73,40.73,40.73,40.73,50.92,40.88,0.0,40.88,40.88,50.12,40.88,40.88,2025-01-01 00:00:01,NaT,17.30,2025-01-01,NaN,17.22,30.24,0.89,3.36,True,True
23,2000110429,"Weeks, Tyler",GK,24.09.2004,200,45.88,28.14,28.14,28.14,28.14,28.14,28.14,27.28,0.0,27.28,27.28,27.28,27.28,27.28,56.09,35.22,35.22,35.22,35.22,35.22,35.22,33.63,0.0,33.63,33.63,33.63,...,0.0,27.23,27.23,27.23,27.23,27.23,57.32,35.21,35.21,35.21,35.21,35.21,35.21,33.60,0.0,33.60,33.60,33.60,33.60,33.60,2025-01-01 00:00:01,NaT,20.27,2025-01-01,NaN,45.88,27.28,1.23,-0.05,True,True
24,2002077757,"Usman, Victor",DM,13.02.2008,0,19.58,26.29,26.29,26.29,26.29,26.29,32.86,25.81,0.0,30.55,25.81,25.81,28.31,26.57,28.29,38.05,38.05,38.05,38.05,38.05,47.56,37.84,0.0,44.77,37.84,37.84,...,0.0,32.41,27.39,27.39,30.04,28.15,28.30,39.29,39.29,39.29,39.29,39.29,49.11,38.74,0.0,45.84,38.74,38.74,42.49,39.50,2025-01-01 00:00:01,NaT,16.88,2025-01-01,NaN,19.58,26.57,0.40,1.58,True,True
25,2002077752,"Cretaro, Sean",GK,14.10.2007,0,48.38,18.43,18.43,18.43,18.43,18.43,18.43,18.36,0.0,18.36,18.36,18.36,18.36,18.36,59.59,27.10,27.10,27.10,27.10,27.10,27.10,26.31,0.0,26.31,26.31,26.31,...,0.0,18.31,18.31,18.31,18.31,18.31,59.59,27.05,27.05,27.05,27.05,27.05,27.05,26.25,0.0,26.25,26.25,26.25,26.25,26.25,2025-01-01 00:00:01,NaT,17.22,2025-01-01,NaN,48.38,18.36,0.00,-0.05,True,True
26,2002077760,"Alcalá, Aitor","DM, AM C",13.09.2007,50,17.61,30.93,30.93,30.93,30.93,30.93,38.08,31.47,0.0,31.47,31.47,38.58,31.47,31.47,24.20,38.88,38.88,38.88,38.88,38.88,47.88,39.47,0.0,39.47,39.47,48.39,...,0.0,33.60,33.60,41.19,33.60,33.60,24.30,40.73,40.73,40.73,40.73,40.73,50.92,40.88,0.0,40.88,40.88,50.12,40.88,40.88,2025-01-01 00:00:01,NaT,17.30,2025-01-01,NaN,17.22,30.24,0.89,3.36,True,True
27,2002077752,"Cretaro, Sean",GK,14.10.2007,0,48.38,18.34,18.34,18.34,18.34,18.34,18.34,18.28,0.0,18.28,18.28,18.28,18.28,18.28,59.59,27.01,27.01,27.01,27.01,27.01,27.01,26.22,0.0,26.22,26.22,26.22,...,0.0,18.31,18.31,18.31,18.31,18.31,59.59,27.05,27.05,27.05,27.05,27.05,27.05,26.25,0.0,26.25,26.25,26.25,26.25,26.25,2025-01-01 00:00:01,NaT,17.22,2025-01-01,NaN,48.38,18.36,0.00,-0.05,True,True
28,2002077764,"Cundy-Camper, Luc",D RC,30.10.2007,0,20.08,34.74,37.22,37.78,30.23,35.77,30.23,29.89,0.0,29.89,29.89,29.89,29.89,29.89,23.00,40.08,42.93,43.58,34.86,41.26,34.86,34.59,0.0,34.59,34.59,34.59,...,0.0,29.94,29.94,29.94,29.94,29.94,22.80,40.31,43.18,43.84,35.07,41.50,35.07,34.64,0.0,34.64,34.64,34.64,34.64,34.64,2025-01-01 00:00:01,NaT,17.17,2025-01-01,NaN,19.68,28.43,0.20,1.51,True,True
29,2002077755,"Dreien, Alexander","AM LC, F C",02.01.2008,0,27.91,39.37,39.37,39.37,39.37,39.37,39.37,43.39,0.0,38.23,47.07,47.07,40.44,48.73,34.10,47.29,47.29,47.29,47.29,47.29,47.29,52.50,0.0,46.26,56.96,56.96,...,0.0,39.55,48.70,49.44,41.84,50.38,33.82,48.05,48.05,48.05,48.05,48.05,48.05,53.11,0.0,46.79,57.62,58.49,49.50,59.44,2025-01-01 00:00:01,NaT,17.00,2025-01-01,NaN,27.80,48.08,0.22,2.30,True,True
30,2002077753,"Effiong, Christopher",AM RLC,09.06.2008,0,22.55,39.70,39.70,39.70,39.70,39.70,39.70,43.78,0.0,47.25,47.47,47.68,48.40,38.72,24.82,43.69,43.69,43.69,43.69,43.69,43.69,48.42,0.0,52.25,52.49,52.72,...,0.0,48.29,48.51,48.73,49.46,39.57,25.19,44.76,44.76,44.76,44.76,44.76,44.76,49.38,0.0,53.29,53.54,53.77,54.59,43.67,2025-01-01 00:00:01,NaT,16.56,2025-01-01,NaN,22.17,38.49,0.76,1.08,True,True
31,5113948,"Fontaine, Liam",D C,07.01.1986,360,19.78,33.80,42.25,33.80,33.80,33.80,33.80,33.21,0.0,33.21,33.21,33.21,33.21,33.97,19.78,34.07,42.59,34.07,34.07,34.07,34.07,33.51,0.0,33.51,33.51,33.51,...,0.0,32.28,32.28,32.28,32.28,33.04,19.50,33.09,41.36,33.09,33.09,33.09,33.09,32.58,0.0,32.58,32.58,32.58,32.58,33.34,2025-01-01 00:00:01,NaT,38.98,2025-01-01,NaN,20.64,35.11,-1.14,-2.07,True,True
32,2002077761,"Gall, Paul","WB L, AM LC",08.03.2008,0,24.49,40.68,33.69,33.69,41.49,33.69,33.69,38.21,0.0,33.23,41.53,40.91,33.23,40.12,29.18,49.34,40.87,40.87,50.32,40.87,40.87,46.60,0.0,40.52,50.65,49.89,...,0.0,33.97,42.46,41.82,33.97,41.01,29.18,50.37,41.72,41.72,51.37,41.72,41.72,47.44,0.0,41.25,51.56,50.80,41.25,49.81,2025-01-01 00:00:01,NaT,16.82,2025-01-01,NaN,24.51,39.71,-0.02,1.30,True,True
33,2002077758,"Gwynne, Jamie","D RC, DM",22.02.2008,0,25.19,34.69,43.36,42.52,34.69,40.32,42.71,33.48,0.0,33.48,33.48,33.48,33.48,34.24,27.32,37.45,46.81,45.91,37.45,43.53,46.11,36.27,0.0,36.27,36.27,36.27,...,0.0,34.83,34.83,34.83,34.83,35.59,27.36,38.63,48.29,47.36,38.63,44.90,48.29,37.21,0.0,37.21,37.21,37.21,37.21,37.97,2025-01-01 00:00:01,NaT,16.86,2025-01-01,NaN,25.17,33.68,0.36,1.91,True,True
34,2002077763,"Harris, Alex","AM RL, ST",18.10.2007,0,15.61,30.81,30.81,30.81,30.81,30.81,30.81,35.35,0.0,35.48,38.32,31.26,38.49,39.07,18.13,34.19,34.19,34.19,34.19,34.19,34.19,39.22,0.0,39.37,42.52,34.69,...,0.0,35.71,38.57,31.46,38.74,39.33,18.23,34.41,34.41,34.41,34.41,34.41,34.41,39.45,0.0,39.60,42.77,34.89,42.96,43.61,2025-01-01 00:00:01,NaT,17.21,2025-01-01,NaN,15.41,38.41,0.30,0.92,True,True
35,2000134437,"Kovacevic, Alex",GK,09.05.2005,460,59.90,39.01,39.01,39.01,39.01,39.01,39.01,36.98,0.0,36.98,36.98,36.98,36.98,37.73,67.06,44.07,44.07,44.07,44.07,44.07,44.07,41.52,0.0,41.52,41.52,41.52,...,0.0,37.16,37.16,37.16,37.16,37.92,67.09,44.31,44.31,44.31,44.31,44.31,44.31,41.75,0.0,41.75,41.75,41.75,41.75,42.51,2025-01-01 00:00:01,NaT,19.65,2025-01-01,NaN,59.65,37.92,0.28,0.00,True,True
36,29037157,"McNerney, Joe",D C,24.01.1990,550,14.56,30.21,37.76,35.45,30.21,30.21,30.21,30.37,0.0,30.37,30.37,30.37,30.37,31.13,14.56,30.31,37.89,35.57,30.31,30.31,30.31,30.48,0.0,30.48,30.48,30.48,...,0.0,29.47,29.47,29.47,29.47,30.23,14.44,29.39,36.74,34.49,29.39,29.39,29.39,29.58,0.0,29.58,29.58,29.58,29.58,30.34,2025-01-01 00:00:01,NaT,34.94,2025-01-01,NaN,15.12,31.84,-0.68,-1.61,True,True
37,2002077765,"Musa, David",D LC,19.07.2008,0,21.75,44.23,44.90,35.92,41.29,35.92,35.92,34.70,0.0,37.89,34.70,34.70,36.71,35.46,24.27,48.18,48.91,39.13,44.98,39.13,39.13,37.90,0.0,41.37,37.90,37.90,...,0.0,39.02,35.74,35.74,37.81,36.50,24.27,49.40,50.14,40.11,46.11,40.11,40.11,38.70,0.0,42.25,38.70,38.70,40.94,39.46,2025-01-01 00:00:01,NaT,16.45,2025-01-01,NaN,21.46,34.53,0.58,1.97,True,True
38,2002077756,"Njoku, Abraham",AM RC,09.01.2008,0,19.81,35.77,35.77,35.77,35.77,35.77,35.77,34.89,0.0,42.77,34.89,42.96,39.45,34.89,22.33,39.52,39.52,39.52,39.52,39.52,39.52,38.75,0.0,47.51,38.75,47.71,...,0.0,44.04,35.92,44.23,40.62,35.92,21.86,40.62,40.62,40.62,40.62,40.62,40.62,39.61,0.0,48.56,39.61,48.77,44.79,39.61,2025-01-01 00:00:01,NaT,16.98,2025-01-01,NaN,19.34,33.76,0.29,2.16,True,True
39,2000231345,"Odei-Larbi, Joel","AM L, ST",27.07.2006,40,29.37,47.91,47.91,47.91,47.91,47.91,47.91,50.25,0.0,49.40,54.51,44.27,53.45,55.34,30.06,48.77,48.77,48.77,48.77,48.77,48.77,51.25,0.0,50.39,55.60,45.15,...,0.0,49.50,54.62,44.36,53.56,55.45,30.07,48.86,48.86,48.86,48.86,48.86,48.86,51.35,0.0,50.49,55.71,45.24,54.62,56.55,2025-01-01 00:00:01,NaT,18.43,2025-01-01,NaN,29.76,55.31,-0.38,0.14,True,True
40,2002077759,"Onana, Fabrice","AM R, ST",14.02.2008,0,26.57,41.40,41.40,41.40,41.40,41.40,41.40,39.83,0.0,45.21,39.83,39.83,49.05,49.79,29.84,45.15,45.15,45.15,45.15,45.15,45.15,43.60,0.0,49.49,43.60,43.60,...,0.0,46.13,40.64,40.64,50.04,50.79,29.87,46.05,46.05,46.05,46.05,46.05,46.05,44.40,0.0,50.40,44.40,44.40,54.68,55.50,2025-01-01 00:00:01,NaT,16.88,2025-01-01,NaN,26.50,49.30,0.45,1.49,True,True
41,2002078880,"Parry, Ian",AM RLC,17.05.2008,0,21.58,35.04,35.04,35.04,35.04,35.04,35.04,37.89,0.0,40.88,41.08,41.25,41.88,34.26,24.50,39.02,39.02,39.02,39.02,39.02,39.02,42.51,0.0,45.87,46.09,46.29,...,0.0,41.25,41.45,41.63,42.26,34.56,24.40,39.34,39.34,39.34,39.34,39.34,39.34,42.72,0.0,46.09,46.31,46.51,47.22,38.53,2025-01-01 00:00:01,NaT,16.63,2025-01-01,NaN,21.58,33.96,0.20,0.60,True,True
42,2002077767,"Spetch, Aarran",WB L,22.09.2007,20,21.85,39.20,32.13,32.13,40.16,35.84,32.13,30.58,0.0,30.58,32.35,30.58,30.58,30.58,24.96,45.24,37.08,37.08,46.35,41.37,37.08,35.59,0.0,35.59,37.65,35.59,...,0.0,30.89,32.68,30.89,30.89,30.89,25.61,46.13,37.46,37.46,46.83,41.79,37.46,35.96,0.0,35.96,38.04,35.96,35.96,35.96,2025-01-01 00:00:01,NaT,17.28,2025-01-01,NaN,22.14,30.49,-0.19,0.40,True,True
43,2002077762,"Stapleton, Leo","D RC, M R",12.09.2007,0,13.56,31.15,32.99,33.49,26.79,32.99,26.79,26.57,0.0,32.57,26.57,26.57,30.04,27.33,19.75,41.74,44.22,44.89,35.91,44.22,35.91,35.87,0.0,43.98,35.87,35.87,...,0.0,34.25,27.93,27.93,31.59,28.69,19.56,42.48,45.00,45.68,36.54,45.00,36.54,36.30,0.0,44.51,36.30,36.30,41.05,37.06,2025-01-01 00:00:01,NaT,17.31,2025-01-01,NaN,12.99,25.91,1.08,2.78,True,True
44,2002077754,"Tongue, Stuart","D LC, DM",08.08.2008,0,19.47,32.41,33.05,26.44,30.73,26.44,32.56,25.16,0.0,25.16,25.16,25.16,25.16,25.92,23.83,39.52,40.29,32.24,37.47,32.24,39.69,31.09,0.0,31.09,31.09,31.09,...,0.0,25.66,25.66,25.66,25.66,26.42,23.83,40.40,41.19,32.95,38.30,32.95,40.57,31.59,0.0,31.59,31.59,31.59,31.59,32.35,2025-01-01 00:00:01,NaT,16.40,2025-01-01,NaN,19.08,24.67,0.40,1.75,True,True
45,2002077757,"Usman, Victor",DM,13.02.2008,0,19.77,27.06,27.06,27.06,27.06,27.06,33.83,26.43,0.0,31.28,26.43,26.43,28.99,27.19,28.19,38.72,38.72,38.72,38.72,38.72,48.41,38.32,0.0,45.35,38.32,38.32,...,0.0,32.41,27.39,27.39,30.04,28.15,28.30,39.29,39.29,39.29,39.29,39.29,49.11,38.74,0.0,45.84,38.74,38.74,42.49,39.50,2025-01-01 00:00:01,NaT,16.88,2025-01-01,NaN,19.58,26.57,0.40,1.58,True,True
46,2002077766,"Watters, Ashley",D LC,07.12.2007,0,19.78,45.43,44.75,42.25,41.23,36.34,41.23,34.25,0.0,34.25,34.25,34.25,34.25,34.25,21.22,47.94,47.23,44.58,43.50,38.35,43.50,36.31,0.0,36.31,36.31,36.31,...,0.0,34.80,34.80,34.80,34.80,34.80,21.60,49.28,48.54,45.82,44.72,39.42,44.72,37.22,0.0,37.22,37.22,37.22,37.22,37.22,2025-01-01 00:00:01,NaT,17.07,2025-01-01,NaN,19.49,33.62,0.39,1.18,True,True